make os 호환

diff --git a/xv6-public/Makefile b/xv6-public/Makefile
--- a/xv6-public/Makefile
+++ b/xv6-public/Makefile
@@ -31,7 +31,11 @@ OBJS = \
 
 # Cross-compiling (e.g., on Mac OS X)
 ifeq ($(shell uname), Darwin) # it only works when in OSX!
- TOOLPREFIX = x86_64-elf-
+TOOLPREFIX = x86_64-elf-
+QEMU = /opt/homebrew/bin/qemu-system-i386
+CC = x86_64-elf-gcc
+LD = x86_64-elf-ld
+CFLAGS = -fno-pic -std=gnu99 -static -fno-builtin -fno-strict-aliasing -O2 -Wall -MD -ggdb -m32 -march=i386 -fno-omit-frame-pointer
 endif
 # TOOLPREFIX = i386-jos-elf
 
@@ -59,35 +63,48 @@ endif
 
 # Try to infer the correct QEMU
 ifndef QEMU
-QEMU = /opt/homebrew/bin/qemu-system-i386
-# QEMU = $(shell if which qemu > /dev/null; \
-# 	then echo qemu; exit; \
-# 	elif which qemu-system-i386 > /dev/null; \
-# 	then echo qemu-system-i386; exit; \
-# 	elif which qemu-system-x86_64 > /dev/null; \
-# 	then echo qemu-system-x86_64; exit; \
-# 	else \
-# 	qemu=/Applications/Q.app/Contents/MacOS/i386-softmmu.app/Contents/MacOS/i386-softmmu; \
-# 	if test -x $$qemu; then echo $$qemu; exit; fi; fi; \
-# 	echo "***" 1>&2; \
-# 	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
-# 	echo "*** Is the directory containing the qemu binary in your PATH" 1>&2; \
-# 	echo "*** or have you tried setting the QEMU variable in Makefile?" 1>&2; \
-# 	echo "***" 1>&2; exit 1)
+QEMU = $(shell if which qemu > /dev/null; \
+	then echo qemu; exit; \
+	elif which qemu-system-i386 > /dev/null; \
+	then echo qemu-system-i386; exit; \
+	elif which qemu-system-x86_64 > /dev/null; \
+	then echo qemu-system-x86_64; exit; \
+	else \
+	qemu=/Applications/Q.app/Contents/MacOS/i386-softmmu.app/Contents/MacOS/i386-softmmu; \
+	if test -x $$qemu; then echo $$qemu; exit; fi; fi; \
+	echo "***" 1>&2; \
+	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
+	echo "*** Is the directory containing the qemu binary in your PATH" 1>&2; \
+	echo "*** or have you tried setting the QEMU variable in Makefile?" 1>&2; \
+	echo "***" 1>&2; exit 1)
 endif
 
+ifndef CC
 CC = x86_64-elf-gcc
+endif
+
 AS = $(TOOLPREFIX)gas
+
+ifndef LD
 LD = x86_64-elf-ld
+endif
+
 OBJCOPY = $(TOOLPREFIX)objcopy
 OBJDUMP = $(TOOLPREFIX)objdump
-CFLAGS = -fno-pic -std=gnu99 -static -fno-builtin -fno-strict-aliasing -O2 -Wall -MD -ggdb -m32 -march=i386 -fno-omit-frame-pointer
+
+ifndef CFLAGS
+CFLAGS = -fno-pic -static -fno-builtin -fno-strict-aliasing -O2 -Wall -MD -ggdb -m32 -Werror -fno-omit-frame-pointer -Wno-error=stringop-overflow=0
+endif
+
 CFLAGS += $(shell $(CC) -fno-stack-protector -E -x c /dev/null >/dev/null 2>&1 && echo -fno-stack-protector)
 ASFLAGS = -m32 -gdwarf-2 -Wa,-divide
 # FreeBSD ld wants ``elf_i386_fbsd''
 LDFLAGS += -m $(shell $(LD) -V | grep elf_i386 2>/dev/null | head -n 1)
+
+ifeq ($(shell uname), Darwin)
 LIBGCC_A = $(shell $(CC) $(CFLAGS) -print-libgcc-file-name)		
 FS=fs.img
+endif
 
 # Disable PIE when possible (for Ubuntu 16.10 toolchain)
 ifneq ($(shell $(CC) -dumpspecs 2>/dev/null | grep -e '[^f]no-pie'),)
@@ -192,6 +209,7 @@ UPROGS=\
 	_project01\
 	_my_test\
 	_lab03\
+	_lab04\
 
 fs.img: mkfs README $(UPROGS)
 	./mkfs fs.img README $(UPROGS)
@@ -261,7 +279,7 @@ qemu-nox-gdb: fs.img xv6.img .gdbinit
 EXTRA=\
 	mkfs.c ulib.c user.h cat.c echo.c forktest.c grep.c kill.c\
 	ln.c ls.c mkdir.c rm.c stressfs.c usertests.c wc.c zombie.c\
-	printf.c umalloc.c my_userapp.c project01.c my_test.c lab03.c\
+	printf.c umalloc.c my_userapp.c project01.c my_test.c lab03.c lab04.c\
 	README dot-bochsrc *.pl toc.* runoff runoff1 runoff.list\
 	.gdbinit.tmpl gdbutil\
 
